# Generated by Django 6.0.7 on 2026-07-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="С какого момента рассылка может быть запущена.",
                        verbose_name="Дата и время начала отправки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="До какого момента разрешено выполнять отправку.",
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана в системе")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена в системе")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mailings",
                        to="recipients.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True, related_name="mailings", to="recipients.recipients", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="SendLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipients.recipients",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог отправки",
                "verbose_name_plural": "Логи отправок",
                "ordering": ["-attempt_time"],
                "indexes": [models.Index(fields=["mailing", "recipient"], name="mailing_recipient_idx")],
            },
        ),
    ]
