# Generated by Django 6.0.7 on 2026-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendlog",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("Не успешно", "Не успешно")], max_length=10, verbose_name="Статус"
            ),
        ),
    ]
