# Generated by Django 6.0.7 on 2026-07-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(help_text="Укажите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body_message",
                    models.TextField(help_text="Введите текст письма", max_length=1000, verbose_name="Текст письма"),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты", max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("first_name", models.CharField(help_text="Укажите имя", max_length=40, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        help_text="Укажите отчество (если есть)",
                        max_length=40,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                ("last_name", models.CharField(help_text="Укажите фамилию", max_length=40, verbose_name="Фамилия")),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Ваш комментарий (необязательно)",
                        max_length=200,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
